##
# docker-compose.yaml
#
# Jonathan Camenzuli
#
# Docker Compose File
#
# Source code is part of my Final Year Project in Computer Engineering (2022/23) entitled
# "Miniature implementation of an IoT-based Smart City"
#
# 17/02/2023
#
#

version: "3.9"
name: "fyp_smart_city_model"
services:
  coap-server:
    container_name: coap-server
    hostname: coap-server
    build: ./coap
    restart: always
    ports:
      - "5683:5683"
    networks:
      - fyp_backend
  
  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: influxdb:2.6.1
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_volume:/var/lib/influxdb
    env_file:
      - influxdb.env
    networks:
      - fyp_backend
      - fyp_frontend
      
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:9.3.6
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - grafana_volume:/var/lib/grafana
    env_file:
      - grafana.env
    networks:
      - fyp_frontend

  ip-lookup:
    container_name: ip-lookup
    hostname: ip-lookup
    build: ./ip_lookup
    restart: always
    ports:
      - "80:80"
    networks:
      - fyp_ip_lookup

networks:
  fyp_ip_lookup:
    driver: bridge
  fyp_backend:
    driver: bridge
  fyp_frontend:
    driver: bridge
volumes:
  influxdb_volume:
    external: true
  grafana_volume:
    external: true