version: "3.9"
name: "fyp_smart_city_model"
services:
  coap-server:
    container_name: coap-server
    hostname: coap-server
    build: ./coap
    restart: always
    ports:
      - "5683:5683"
    networks:
      - fyp_backend
  
  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: influxdb:2.6.1
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_volume:/var/lib/influxdb
    env_file:
      - influxdb.env
    networks:
      - fyp_backend
      - fyp_frontend
      
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3001:3001"
    networks:
      - fyp_frontend
    volumes:
      - grafana_volume:/var/lib/influxdb

networks:
  fyp_backend:
    driver: bridge
  fyp_frontend:
    driver: bridge
volumes:
  influxdb_volume:
    external: true
  grafana_volume:
    external: true